# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create and set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Ensure the TypeScript compiler is executable and build the project
RUN chmod +x ./node_modules/.bin/tsc && npm run build

# Ensure the built entrypoint is executable
RUN chmod +x ./build/index.js

# Run the MCP server
CMD ["node", "./build/index.js"]
